### ISSUE TITLE
Wrong docs for encase?

### ISSUE THREAD

**Issue by dypsilon** [Avaq/Fluture#20]
I sense that the docs for encase are wrong, but I wasn't able to write clearer docs. The problem is, that encase returns a function, not a Future. But I have hard times to put into writing what the new function does.

**Comment by Avaq** [comment]
Hi @dypsilon, thanks for your concerns. I share them with you. The thing is; `encase` is a *binary, curried* function. It takes a function and a value, and returns a Future which when forked calls the function with the value. So technically, the documentation is correct:

> Creates a Future which resolves with the result of calling the given function with the given value

The problem is that this is not how we're using that function. It is *meant* to be partially applied. We're more interested in the properties of the "intermediate" function (that you get from partial application) than the fact that there's a Future at the end. The phrasing implies that it's some sort of constructor, which it is *technically*, but not *practically*.

Maybe I can make an amendment to the current documentation, something like: "Partially applying `encase` with a function `f` allows us to create a "safe" version of `f`. Instead of throwing an error, the encased version returns a Future which might reject."

**Comment by dypsilon** [comment]
Your description is very good and precise, I think adding it to the docs will help new users of Fluture.

In my opinion an example of uncurried usage, in addition to the curried one, would be helpful. Something along the lines of:

~~~javascript
const data = '{"foo" = "bar"}';
const future = Future.encase(JSON.parse, data);
future.fork(console.error, console.log)
//> [SyntaxError: Unexpected token =]
~~~

This example is consistent with the current documentation.

**Comment by Avaq** [comment]
What do you think of #21, @dypsilon?

**Comment by dypsilon** [comment]
Looks great!
