### ISSUE TITLE
Should reject and resolve always be executed async?

### ISSUE THREAD

**Issue by jordalgo** [Avaq/Fluture#27]
The computation can be run sync but reject or resolve execute async to make it more predictable. Thoughts?

**Comment by Avaq** [comment]
I've considered this several times, and always reached the conclusion that because of Future's laziness, there is no need to postpone running the continuations to the next tick.

In many async API's, like EventEmitter, you might end up with a situation where listeners may not yet have been attached before the event is emitted, if the emitter were to emit the event in the same tick that the listeners are attached. But since Futures are cold until you call `fork`, and continuations are provided to `fork`, we can always be sure that the continuations are called in a timely manner.

Personally I've not run into a situation where the predictability of async/sync resolution was problematic. Though I'd be interested to learn about your experiences, especially if you found a case where something unexpected happened.

**Comment by jordalgo** [comment]
@Avaq Yeah, I think I came to this same conclusion myself over the past few days (I also removed it from my Task implementation). For types like signals or Observables with multiple subscribers it's nice to separate out the notifications into separate call stacks for easier debugging but with Futures, since it's a one to one relationship and they are lazy it's probably not needed. 👍
