### ISSUE TITLE
Add option to create Flutures without type checking.

### ISSUE THREAD

**Issue by jordalgo** [Avaq/Fluture#29]
I think it would be nice if you could opt-out of runtime type checking and create a dev and prod version of this type. Similar to that in [sanctuary-js](https://github.com/sanctuary-js/sanctuary#type-checking)

**Comment by Avaq** [comment]
The sole reason Sanctuary has an opt-out from type-checking is because type-checking in Sanctuary is incredibly advanced, yet very taxing on performance (to the point where programs running *with* type-checking run about ten times as slow as without).

In Fluture's case, type-checking costs next-to-no performance (at the cost of some pretty repetitive code). I wouldn't be surprised if adding the option to disable it would actually end up costing performance, besides making the API less pleasant.

Are there any non performance-related reasons you would want to disable type-checking?

**Comment by jordalgo** [comment]
It was mostly for performance reasons but I haven't done any benchmarking with a non type-checking version of Flutures. I thought that with long Future chains you could probably get some improvement in performance if you weren't type-checking but perhaps, as you say, it's pretty negligible. 

I'm also a little weary of doing so much type checking in libs as I feel like it's up to the developers/users of the lib to either add their own unit tests, linting, preventative measures, etc... It would also make the source code of the lib cleaner and easier to read.

**Comment by Avaq** [comment]
My view is that the faster a program is able to fail, the better. The cases where I'm throwing a TypeError would otherwise have eventually lead to a much more cryptic error somewhere down the track (like `m._f is not a function`, or `cannot read property _f of undefined`). These errors would originate from within the library, and would've been difficult to prevent with plain JavaScript.

The reason that type-checking in Fluture is so cheap, is because I used some techniques for optimizing them:

* The type-checks live in their own functions, which are expected to be called with similar types every time. This allows v8 to optimize these functions.
* The actual `throw` statement lives yet one level deeper, allowing chrome to in-line the checks. The functions with the `throw` statements cannot be in-lined, but the code never reaches that path (unless it is already failing).
* All of the weight of creating the error message, casting values to string, concatenating the messages, etc. is moved to behind the initial type-check, so is not executed unless we're already failing.
* The type-checks themselves are usually just one or two simple if-statements.

So we end up with one or two in-lined if-statements, optimized where possible, per method. Of course, a version of Fluture without them would perform somewhat better, but a version of Fluture where all of that lives behind an additional `if(typechecking === true)`-check would certainly perform slower.

My original goal for Fluture was to create a stand-alone, type-checked version of Ramda Fantasy Future, because in working with Futures, I realized debugging the cryptic error messages was one of the biggest slowing-down factors. In adding type-checks to the library, I knew people would raise questions about performance, so I made sure to optimize, and as it stands, I believe Fluture is still the best performing Future library out there, despite its type-checking. So releasing a version of Fluture where the type-checks are removed is more than out-of-scope for me.

**Comment by jordalgo** [comment]
@Avaq Thanks for the detailed response! I agree that the faster a program can fail the better and I'm definitely going to employ some of those optimization techniques in my lib if I decide to do some type checking. I really don't have strong feelings about removing the type-checking in this lib and the issue I raised was more of a suggestion/question. At some point I may experiment with a technique similar to what [debug](https://github.com/visionmedia/debug) uses as a method for type checking in dev mode but feel free to close this issue.
